# Generated by Django 5.2.12 on 2026-03-21 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_remove_child_height_remove_child_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(default='book-outline', max_length=100)),
                ('color', models.CharField(default='#6366F1', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('pediatric', 'Педиатрия'), ('neuro', 'Невролог'), ('speech', 'Логопед'), ('psych', 'Психолог'), ('ortho', 'Ортопед')], max_length=30)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('image', models.URLField()),
                ('color', models.CharField(default='#6366F1', max_length=20)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('max_age', models.PositiveIntegerField(default=180)),
                ('online', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('consult_type', models.CharField(choices=[('video', 'Видеочат'), ('chat', 'Чат'), ('offline', 'Офлайн')], default='video', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='families.child')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consults.doctor')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
