# Generated by Django 5.2.12 on 2026-03-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('health', 'Здоровье'), ('psych', 'Психология'), ('edu', 'Развитие'), ('food', 'Питание')], max_length=20)),
                ('tag', models.CharField(max_length=100)),
                ('read_time', models.CharField(default='5 мин', max_length=30)),
                ('image', models.URLField()),
                ('color', models.CharField(default='#6366F1', max_length=20)),
                ('min_months', models.PositiveIntegerField(default=0)),
                ('max_months', models.PositiveIntegerField(default=72)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
