# Generated by Django 5.2.12 on 2026-03-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('ok', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.activitycategory'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_age_months',
            field=models.PositiveIntegerField(default=72),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='activitycompletion',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activitycompletion',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
