# Generated by Django 5.2.12 on 2026-03-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_remove_child_height_remove_child_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('template_type', models.CharField(choices=[('mchat', 'M-CHAT'), ('early_dev', 'Early Development')], default='mchat', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_age_months', models.PositiveIntegerField(default=0)),
                ('max_age_months', models.PositiveIntegerField(default=999)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('result_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('done', 'Done'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('target_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='families.child')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='screenings.screeningtemplate')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('answer_type', models.CharField(choices=[('yes_no', 'Yes / No'), ('single_choice', 'Single Choice')], default='yes_no', max_length=30)),
                ('risk_answer', models.CharField(blank=True, max_length=20, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='screenings.screeningtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ScreeningAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='screenings.screeningquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='screenings.screeningsession')),
            ],
            options={
                'ordering': ['question__order'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
